from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manual(object):
    def setupUi(self, Manual):
        Manual.setObjectName("Manual")
        Manual.resize(1920, 1000)
        Manual.setMinimumSize(1920, 1000)
        Manual.setMaximumSize(1920, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/User\'s manual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Manual.setWindowIcon(icon)
        Manual.setAutoFillBackground(False)
        self.treeWidget = QtWidgets.QTreeWidget(Manual)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 430, 1000))
        self.treeWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.textBrowser = QtWidgets.QTextBrowser(Manual)
        self.textBrowser.setGeometry(QtCore.QRect(430, 0, 1490, 1000))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.raise_()
        self.treeWidget.raise_()

        self.retranslateUi(Manual)
        QtCore.QMetaObject.connectSlotsByName(Manual)

    def retranslateUi(self, Manual):
        _translate = QtCore.QCoreApplication.translate
        Manual.setWindowTitle(_translate("Manual", "User\'s manual"))
        self.treeWidget.headerItem().setText(0, _translate("Manual", "Catalog"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Manual", "Cover"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Manual", "1　System overview"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Manual", "1.1　Background Information"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Manual", "1.2　Overall Introduction of System"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Manual", "2　Description of the main functions"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Manual", "2.1　Turn on/off camera"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Manual", "2.2　Import videos or images"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Manual", "2.3　Export files"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Manual", "2.4　Import models"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("Manual", "2.5　Instant Preview"))
        self.treeWidget.topLevelItem(2).child(5).setText(0, _translate("Manual", "2.6　Detection"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Manual", "3　Description of the miscellaneous functions"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Manual", "3.1　Train models"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Manual", "3.2　Options"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("Manual", "3.3　User\'s manual"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("Manual", "3.4　Feedback"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("Manual", "3.5　About"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Manual", "4　Description of the models"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Manual", "4.1　U-net"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Manual", "4.2　Resnet50-Unet"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Manual", "5　Shortcut keys"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("Manual", "6　Update log"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("Manual", "6.1　Version 0.8"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("Manual", "6.2　Version 1.0"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.cover = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict."    \
                     "dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { "\
                     "white-space: pre-wrap; }\n</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; " \
                     "font-weight:400; font-style:normal;\">\n<table border=\"0\" style=\" margin-top:50px; margin-"   \
                     "bottom:0px; margin-left:50px; margin-right:0px;\" width=\"756\" cellspacing=\"0\" cellpadding="  \
                     "\"0\">\n<tr>\n<td width=\"98\" style=\" vertical-align:top; padding-left:0; padding-right:0; "   \
                     "padding-top:0; padding-bottom:0;\">\n<p style=\" margin-top:18px; margin-bottom:12px; margin-"   \
                     "left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"images/logo.png\"" \
                     " width=\"83\" height=\"82\" style=\"vertical-align: top;\" /> </p></td>\n<td width=\"1000\" "    \
                     "style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n<p style=\" "     \
                     "margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; "    \
                     "text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:36pt; font-weight:600;\">"      \
                     "Surgical Navigation System</span> </p></td></tr></table>\n<p align=\"center\" style=\" margin-"  \
                     "top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent"\
                     ":0px;\"><img src=\"images/manual-1.png\"/></p>\n<p style=\"-qt-paragraph-type:empty; margin-top:"\
                     "12px; margin-bottom:12px; margin-left:50px; margin-right:0px; -qt-block-indent:0; text-indent:"  \
                     "0px;\"><br /></p>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left"\
                     ":0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version: V1.0</p>\n<p align=\""   \
                     "center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-"  \
                     "block-indent:0; text-indent:0px;\">Author: Dai Linxin</p></body></html>"
        self.textBrowser.setHtml(self.cover)


class win_Manual(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(win_Manual, self).__init__(parent)
        self.ui = Ui_Manual()
        self.ui.setupUi(self)
        self.init_slots()
        self.header = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"\
                     "p, li { white-space: pre-wrap; }\n"\
                     "</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"\
                     "<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"

    def init_slots(self):
        self.ui.treeWidget.clicked.connect(self.onClicked)

    def onClicked(self, index):
        if self.ui.treeWidget.currentItem().text(0) == "Cover":
            self.ui.textBrowser.setHtml(self.ui.cover)
        elif self.ui.treeWidget.currentItem().text(0) == "1.1　Background Information":
            self.ui.textBrowser.setText(self.header +
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">1.1　 Background Information</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:24px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Although the introduction of TME, the standard surgical procedure for rectal cancer, has reduced local recurrence rates and significantly improved overall survival, TME surgery remains technically challenging with an average learning curve of more than 40 cases per surgeon, because it requires knowledge of the complex anatomy of the deep pelvis and precise anatomical techniques. It is also essential to protect the pelvic autonomic nerves that are misshaped near the resection area to avoid postoperative urinary incontinence and sexual dysfunction, as these postoperative functional sequelae affect the quality of life of up to 85% of patients after rectal cancer surgery. In TME, the Holy plane space is an avascular space composed of loose connective tissue fibers between the mesorectal fascia and pelvic wall fascia. During TME surgery, active identification and mobilization along the Holy plane space contribute to the safe and accurate completion of high-quality TME surgery. It can improve the overall survival rate of patients and reduce postoperative functional sequelae. However, even for experienced surgeons, it is sometimes difficult to identify the gap between different tissues of embryonic origin, so it is difficult to visually identify this complex and indistinct anatomical gap.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">With the recent rapid development of artificial intelligence, various image recognition techniques have also been developed. In recent years, Convolutional Neural Networks (CNN) are mainly used for image recognition tasks based on deep learning. In laparoscopic rectal cancer surgery, deep learning-based image recognition has been applied to automatically identify the location of key anatomical structures during the operation, such as prostate, inferior mesenteric artery and surgical instruments during TaTME. The development of image recognition algorithms has been extensively studied using laparoscopic imaging data in recent years. Based on the hypothesis that integrating surgical guidance into a minimally invasive surgical system can significantly improve surgical quality and reduce quality variation between surgeons, it will have the potential to be used as a fully automated image-guided surgical system and may improve surgical safety, efficiency, and skill balance. In this study, we used state-of-the-art CNN-based algorithms to construct and evaluate a deep learning model for automatic segmentation of the Holy plane gap during laparoscopic rectal cancer surgery by exploring the potential of deep learning-based phase recognition (a prerequisite for context awareness) and target structure segmentation, and to evaluate the feasibility of image-guided laparoscopic TME. It helps surgeons to realize the automatic identification of the Holy plane gap in laparoscopic rectal cancer surgery, and contributes to the safe and accurate completion of high-quality laparoscopic TME surgery.</span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "1.2　Overall Introduction of System":
            self.ui.textBrowser.setText(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">1.2　 Overall Introduction of System</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:24px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">As shown in Figure 1, this system can be divided into 5 areas: file tables, preview area, detection operating area, main functional area and menu bar. The </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">file tables</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> include the model table and the file table, which are used to upload model files and video and image files respectively. The </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">preview area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is used to preview the results predicted by the selected model. The user can customize the preview of the original image, the mask image and the image with labels on the basis of the original image. Users can set preferences for the results displayed in the preview area through the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">detection operation area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">. In addition, starting, pausing and stopping detection are also operated in this area. The main functions of the system are realized through the</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\"> main functional area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">, including turn on/off camera, import videos, import images, export results, import models and train models.</span><span style=\" font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">menu bar</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is the menu entry of all functions of the system, and the corresponding functions can be realized by clicking the corresponding option in the menu.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-2.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_x0000_t75\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 1</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">System main interface function partition</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "2　Description of the main functions":
            self.ui.textBrowser.setHtml(self.header +
                "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span>The main function of the system is detecting imported videos or images, therefore, this chapter mainly focuses on the related functions of detecting video or pictures.</span> </p>\n")
        elif self.ui.treeWidget.currentItem().text(0) == "2.1　Turn on/off camera":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">2.1  Turn on/off camera</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In practical application, the user mainly detects the image acquired by the surgical instrument by passing it to the computer, and this can be achieved through the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">turn on/off camera</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> function. Users can implement this function from the main functional area and [File]-[Open]-[Camera] in the menu bar. As for the device number passed by the camera, you can set it in the options interface. If the device number is set incorrectly, the camera may fail to open.</span><span style=\" font-size:12pt;\"> </span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "2.2　Import videos or images":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"OLE_LINK1\"></a><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">2.2　Import videos or images</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In order to facilitate the testing of the accuracy of the model, the system allows users to upload video or image files and detect them through the</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\"> import videos</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">import images</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> functions. Users can implement this function from the main functional area and [File]-[Open]-[Videos…]/[Images…] in the menu bar, and can also import video or picture files by dragging and dropping them (as shown in Figure2).</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Import videos</span><span style=\" font-family:\'宋体\'; font-size:12pt;\">：</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Pop up the file selector (multiple select), in the file selector you can browse mp4, avi, wmv, mov, mkv, flv file types and all types of files.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Import images</span><span style=\" font-family:\'宋体\'; font-size:12pt;\">：</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Pop up the file selector (multiple select), in the file selector you can browse jpg, png, bmp, tiff file types and all types of files.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The uploaded video or picture files will be displayed in the file table, and the system will automatically set </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">not start</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> state(<img src=\"images/not started.png\" width=\"30\" height=\"30\" />)</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and set all files just uploaded checked (user can specify that only the checked files will be detected). In addition, the first image uploaded or the first frame of the uploaded video will be displayed in the preview area.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"images/manual-3.png\"/>　　<img src=\"images/manual-4.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_x0000_i1026\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 2</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Import a video file by dragging and dropping</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "2.3　Export files":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">2.3　Export files</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">When the user performs the test, the system will decide whether to store the prediction results according to the user\'s setting. If the setting is to store the prediction results, the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Export files</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> function will be enabled. Users can implement this function from the main functional area and [File]-[Save as…]. After clicking the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Export files</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> button in the main interface or </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Save as</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> in the menu bar, a new interface will pop up (as shown in Figure 3).</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-5.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_x0000_t75\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 3</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Video export interface</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In the new interface, the user can see the name, the path, the image type, and the parameters of the video file to be exported. In the progress bar area, the user can see the progress of the video export, the estimated time and the remaining time. In addition, the user can modify the export path and encoding method of the video file. If the video is set to be compressed in the setting interface, the bit rate of the exported video can be set here (which is meaningless if the video is set not to be compressed). The user can pause or stop the export process at any moment.</span><span style=\" font-size:12pt;\"> </span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "2.4　Import models":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">2.4　Import models</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Models are essential for detecting videos or images, and if you start detection before uploads, the system will report errors and stop detection. Model files can be imported into the model table through the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Import models</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> button in the main interface or [File]-[Model] in the menu bar. Similar to video or image files, users can also drag and drop the model files directly into the model table to import. After importing the model, the system will automatically determine the model type according to the filename. If the model type cannot be determined from the filename, the default is the Resnet50-Unet model. Users can modify the model type in the Type column of the model table. It\'s important to make sure the model type is accurate, or the prediction will fail.</span><span style=\" font-size:12pt;\"> </span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "2.5　Instant Preview":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_Hlk146999726\"></a><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">2.5　Instant Preview</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">As mentioned above, after importing the video or image files, the first image uploaded or the first frame of the uploaded video will be displayed in the preview area. Click any file in the file table, and its preview image will be displayed in the preview area. During the detection process, the preview area will display the prediction results of the video or picture in real time. Below the preview area, users can set the preview effect at any moment. The parameters that can be set are as follows:</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The content of the display: Including the original image, the mask image, and the label result (as shown in Figure 4), the default is the label result (the system will automatically adjust after starting the prediction).</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The label pattern: Including the color of the label and the size of the line, defaults to white and 5 pixels.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The threshold for converting soft prediction to hard prediction: The default value of the threshold is 0.51 for Resnet50-Unet model and 0.74 for U-net model, which is the optimal value obtained according to the prediction results of existing data sets.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Maximum frame rate (Max FPS): If empty, it is equal to the original frame rate of the video. Users can set it in the setting interface so that the system can automatically set the best maximum FPS according to the processing speed of the user\'s computer.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-6.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:10.5pt;\">(a)  The mask image of </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:10.5pt; font-style:italic;\">011.jpg</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-7.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:10.5pt;\">(b)  The label result of </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:10.5pt; font-style:italic;\">011.jpg</span></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 4</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The same picture in different display modes</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "2.6　Detection":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">2.6　Detection</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Detecting the part of interest to the user is the core function of this system. There are two prerequisites to enable the detection function, namely, the detection source and the model. If the camera is opened, the source of detection is the video signal incoming from the camera. If the videos or images are imported, the source of detection is the video and image files checked in the file table (users can also set to detect all files), and the detection order is from top to bottom. </span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">After the detection starts, the status of the detected file in the file table will be set to </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">processing(<img src=\"images/processing.png\" width=\"30\" height=\"30\"/>). The system will hide the file table area by default, and enlarge the preview area in equal proportion, so that its width is equal to the width of the preview box. Users can set whether to adjust the preview area in the setting interface. Generally speaking, the real-time detection will be delayed due to the processing speed of the computer. You can avoid the delay by setting the maximum FPS or letting the system set the maximum FPS automatically. During the detection process, the user can pause or stop the detection. </span><a name=\"OLE_LINK2\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">I</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">t is worth noting that if the detection of the image or video file is stopped, it is considered to have completed the detection of the file and cannot be detected again. Although stuttering is inevitable, it is still possible to perform arbitrary actions in the system during the detection process.</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Finally, If the detection is successful, the status of the file is set to finish(<img src=\"images/finish.png\" width=\"25\" height=\"25\"/>), and if you have previously allowed the detection results to be stored, you can also export the detection results locally via </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Export files</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">. If the detection fails, the system will give an error and automatically stop the detection, in which case the file loading will be set to fail(<img src=\"images/fail.png\" width=\"25\" height=\"25\"/>). Regardless of success, the system will automatically save the detection results to a local log file, whose default path is the system directory. The output includes the end time, the detection source, the duration of the video (camera, video file)/the number of files tested (image file), and the system running time. If the detection fails, an error code is displayed instead of the elapsed time.</span><span style=\" font-size:12pt;\"> </span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "3.1　Train models":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">3.1　Train models</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">This system provides users with the function to train the model by themselves, and its interface is shown in Figure 5. It can be clearly seen from Figure 5 (b) that the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Train models</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> interface can be divided into 4 sections, which are the file tables area, the preferences setting area, the action area and the progress status area.</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-8.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(a)  Model training interface before starting training</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-9.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(b)  Model training interface after starting training</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 5　The interface of </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">train models</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\"> File tables area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> contains two tables for uploading original images and mask images. There are 4 columns in both tables, the first column is the check boxes, and clicking the check box at the head of the table can select all the pictures in the table, the second column is the thumbnail of the picture files, the third column is the file name of the pictures, and the fourth column is the data set to which the pictures belong (training set, validation set, and prediction set), which is generally determined by </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">sequentially distribute</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">randomly distribute</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> in the setting area. There are two buttons which are </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">import</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">delete</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> below the table. The delete function can only be used when there are pictures in the table, and the deleted ones are the pictures whose checkbox is checked. Like the tables in the main interface, in addition to the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">import</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> button, users can also drag and drop image files directly into the table. The imported original images and mask images are required to have the same number and the file names correspond to each other, otherwise the training will not work properly after that.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Parameter setting is essential for training, and the user can adjust the hyperparameters during training through the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">preferences</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">. The items you can set are as follows:</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Partition: The proportion of training set, validation set and prediction set. After setting, you can distribute the original images and mask images according to your plan through the buttons of </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">sequentially distribute</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">randomly distribute. </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">As for </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">sequentially distribute</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">, the original images and the mask images are proportionally allocated into three data sets from top to bottom according to the order of training set, validation set and prediction set. </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">Randomly distribute</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is to randomly select the corresponding number of images (the original image and the mask image correspond in pairs) according to the proportion and assign them to the three datasets.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Hyperparameters: Hyperparameters are the parameters whose values are set before starting the learning process, including learning rate, epochs, training batch size, validation batch size and whether to pretrain.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Learning rate: The update of network parameter θ depends on the gradient error and the learning rate: the larger the learning rate is, the larger the step size of parameter θ update is. The smaller the learning rate, the smaller the update step of the parameter θ. In the training phase of neural network, adjusting the learning rate of gradient descent algorithm can change the update amplitude of network weight parameters.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Epochs: An epoch is the process of training once using all the samples in the training set. When a complete data set has passed through the neural network once and returned once, that is, a forward propagation and a back propagation have taken place, and this process is called an epoch.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Batch size: Batch size refers to the number of training examples in each minibatch when we train a neural network with backpropagation through an optimization algorithm based on stochastic gradient descent. A larger batch size leads to faster training, a larger memory footprint, and slower convergence.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Pretrain: Pretraining allows us to use as much training data as possible to extract as many common features as possible, which can make the model less burdened with learning a specific task. After checking the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">pretrain</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> check box, you can select the model for pretraining.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Evaluation indexes: Indexes used to evaluate the performance of the trained model. Including dice score, positive predictive value (PPV), negative predictive value (NPV), recall, sensitivity, specificity.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Dice score: Dice score belongs to F1 score and is the harmonic mean of precision and recall, which is calculated as</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-formula1.png\"/></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">     Where TP is pixels that are actually positive and predicted to be positive, FP is pixels that are actually negative and predicted to be positive and FN is pixels that are actually positive and predicted to be negative.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">PPV: The proportion of the quantity predicted correctly in the positive sample, which is calculated as</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-formula2.png\"/></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> </span><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">NPV: The proportion of the quantity predicted correctly in the negative sample, which is calculated as</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-formula3.png\"/></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">       Where TN is pixels that are actually negative and predicted to be negative. </span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Sensitivity: The fraction of samples that were predicted to be positive were actually positive, which is calculated as</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-formula4.png\"/></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\"> </span><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">l</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Specificity: The fraction of samples that were predicted to be negative were actually negative, which is calculated as</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-formula5.png\"/></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Save: After training, you can save the trained model and logs of the training process locally. The user can choose whether to save a model for each epoch and the storage path of the model and logs.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\"> action area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> contains 3 buttons: </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Start, Stop</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">, and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Reset</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">. Once the preferences are set, you can start the training via </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Start</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">. There will be obvious lags in the training process. If you want to stop the training because you need to use other functions in the system or other reasons, you can click the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Stop</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> button. </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Reset</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> can restore each parameter in the preferences setting to the initial setting of the system, whose default value is shown in Figure 5. The system will not prompt after clicking </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Stop</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Reset</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">, so users need to be careful to use these two functions.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-weight:600;\">progress status area</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">, in addition to the progress bar, you can see how long the training has elapsed and how long the system has estimated to be left. In addition, you can see real-time information about the training below the progress bar, which is composed of the following:</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Action: Training or validation.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Epoch: The current epoch / total epochs.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Batch: The current batch / total batches each epoch.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Loss function: The BCEWithLogitsLoss function, which is actually a combination of Sigmod and Binary Cross Entropy (BCE) loss function, and its Loss value is calculated by the formula as follow:</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-formula6.png\"/></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">W</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">here </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">ω</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is a hyperparameter and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">n</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is the number of training sessions; </span><a name=\"_x0000_i1025\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">denotes the label of sample </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">n</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">; </span><a name=\"_x0000_i1025\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">represents the probability that sample </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">i</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is predicted to be positive. Its calculation results retain 8 decimal places</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Wingdings\'; font-size:12pt;\">Ø</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Learning rate: The learning rate drops by half with each epoch.</span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "3.2　Options":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">3.2　Options</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The specific location of options is [Setting]-[Options…]. The options module is divided into general options and export options. In the general options, you can set preview interface, capture device number, GPU number, whether to record test results, storage path, automatically set threshold, and automatically set maximum frame rate.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(1) Preview size: It is used to set the size of the preview interface and whether the aspect ratio should be maintained. In addition, it can set whether the system window should be filled when testing. It is worth noting that if maintaining aspect ratio is checked, the preview screen will automatically scale up when testing (as shown in Figure 6), and if the option is unchecked, it will only expand horizontally.</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-10.png\"></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_x0000_t75\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 6</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Preview interface during detection when </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Show full screen of preview when detecting</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">maintain aspect ratio </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">are both checked</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(2) Capture device number: It is used to detect the device number that can be entered. By clicking check available devices, the signal source of 0-9 numbered device can be automatically detected (as shown in Figure 7).</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-11.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"_x0000_i1026\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 7</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Check available devices</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(3) GPU number: The GPU number to use, users without a GPU can ignore it.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(4)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Log test results: Whether to log test results or not, this option is set to avoid excessive memory consumption. Users with more memory can ignore it. The option is divided into three sub-options according to the input source, namely camera, video, picture, and each input source can be set to automatically record, automatically do not record, or every query. </span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(5) System log storage path: The system log storage directory. The default is the folder where the system files are located.</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(6)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Temporary files storage paht: Temporary files storage directory. The default is /temp/, which is the directory of system files.</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(7)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Automatically set the threshold for hard prediction. The threshold is set according to the author\'s experience. </span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(8) Automatically set the maximum FPS: This will automatically set the maximum FPS, which is the maximum number of frames per second. This setting prevents video delay caused by lower frame rates. When video or camera detection is enabled, the recommended maximum frame rate is displayed on the right.</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In the output options, you can set the size of the output video, whether the output should start automatically, the default output path, and whether the video should be compressed.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(1)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Export size: It is used to set the size of the output video, which can be set to the original video size or custom size. </span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(2)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Automatic start: It is used to set whether the output will start automatically. If not, the Export option window will pop up after clicking Export in the main interface. </span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(3)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Default export path: This is used to set the default export path, which can be set to the original video path or a custom path.</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(4)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Video compresssion: This specifies whether the video should be compressed or not, and sets the default output video bitrate if it is. Note that due to technical limitations, compressing the video will take twice as long as the normal export. (The last word of the bottom small word should be export)</span></p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Restore Defaults</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> is used to restore default settings, as shown in Figure 8.</span><span style=\" font-size:12pt;\"> </span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-12.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><a name=\"图片_x0020_1\"></a><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 8  Options interface (default settings)</span><span style=\" font-size:12pt;\"> </span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "3.3　User\'s manual":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">3.3  User\'s manual</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In order to make it more convenient for users to learn and get familiar with the use of this system through the user’s manual, the author has embedded the user’s manual into the system, and the specific location is [Help]-[User’s manual].</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-13.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 9  User’s manual</span></p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "3.4　Feedback":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">3.4  Feedback</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">In order to collect user feedback and continuously improve the system, this system has set up a feedback function. Users can open the feedback interface from [Help]-[Feedback...]. This interface contains three required pieces of information, which are the user\'s Email, comment content, and captcha (see Figure 10). User Email is collected in order to respond to user feedback in a timely manner and keep in touch. The captcha is set to prevent users from malicious spammers, but in order to save time, only 4-digit captcha is set, and it can be replaced by clicking the captcha. After the user submits the opinion, the opinion content will be directly sent to the author\'s email address, so as to collect the user\'s opinion.</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-14.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 10  Feedback interface</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "3.5　About":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">3.5  About</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">From [Help]-[About], you can open the About interface, where you can see the system logo, version number, brief description and copyright owner. The interface is shown in Figure 11.</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-15.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 11  About interface</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "4　Description of the models":
            self.ui.textBrowser.setHtml(self.header +
                "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span>As of version 1.0, the system supports two kinds of deep learning models, Resnet50-Unet model and traditional U-net model. A brief description of these two models is given in the following.</span> </p>\n")
        elif self.ui.treeWidget.currentItem().text(0) == "4.1　U-net":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">4.1  U-net</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">U-Net is a classical network for few-shot segmentation, which belongs to a variant of the fully convolutional network. It is mainly used to solve the problem of biomedical images, and has been widely used in various directions of semantic segmentation due to its good effect. Unet can be mainly divided into three parts, which are the feature extraction part on the left, the stitching part in the middle and the upsampling part on the right. The feature extraction part on the left is a contraction network, which is similar to the compression operation. The size of the image is reduced through four downsampling. In this continuous downsampling process, the feature extraction is shallow information. The purpose of the stitching part in the middle is to fuse the feature information, so that the deep and shallow information are fused together. When stitching, not only the image size, but also the feature dimension should be the same. The right upsampling part is also called expansion network, which mainly makes the size of the image larger and extracts the deep information. In the process of upsampling, the number of channels of the image is halved, which is opposite to the change of the number of feature extraction channels on the left. In the process of upsampling, the information of the left shallow layer is fused, that is, the left features are spliced. The network architecture is shown in Figure 12.</span></p>\n"
                "<p align=\"center\"><img src=\"images/manual-16.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 12  The network architecture of U-net</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "4.2　Resnet50-Unet":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">4.2  Resnet50-Unet</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">ResNet50-Unet combines the residual structure with U-Net and uses ResNet-50 convolutional neural network for downsampling, so that the model is optimized as follows:</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(1) Deepening the number of network layers improves the segmentation accuracy of the network;</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(2) More jump connections can be added in the middle of the network, so that the background semantic information of the image can be better combined for multi-scale segmentation;</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(3) Resnet has the advantage of fast convergence and reducing the amount of model data;</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(4) Resnet makes the model easier to train, which not only prevents model degradation, but also prevents the gradient from disappearing and the Loss from converging.</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The model structure of ResNet50-Unet is shown in Figure 13.</span></p>"
                "<p align=\"center\"><img src=\"images/manual-17.png\"/></p>\n"
                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 13  The network architecture of Resnet50-Unet</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "5　Shortcut keys":
            self.ui.textBrowser.setHtml(self.header +
                "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">5　Shortcut keys</span> </p>\n"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Common shortcuts in Surgical Navigation System are as follows:</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">F1: User’s manual</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">F5: Start detection</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Ctrl+P: Pause / Continue detection</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Esc: Stop detection</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Ctrl+S: Export results (Save as)</span></p>"
                "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"></span></p>\n")
        elif self.ui.treeWidget.currentItem().text(0) == "6.1　Version 0.8":
            self.ui.textBrowser.setHtml(self.header +
            "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">6.1  Version 0.8</span> </p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(1) Adds setting module, providing users with personalized usage preferences and export options.</span></p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(2) Adds the function of setting the maximum frame rate.</span></p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">As mentioned in Chapter 3, this function is mainly to prevent intraoperative video delay and can be set in the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Max FPS</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> item of the main interface and can be adjusted during the detection process. </span><span style=\" font-size:12pt;\"> </span></p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(3) Adds drag-and-drop import functionality and supports bulk video import.</span><span style=\" font-size:12pt;\"> </span></p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">This version of the system supports the import of models and video/image files by dragging and dropping files into the </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Models</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> and </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt; font-style:italic;\">Files</span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\"> tables, saving the time of opening the file selection interface. In addition, this version supports bulk import of video files.</span><span style=\" font-size:12pt;\"> </span></p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(4) Beautifies interface, as shown in Figure 14.</span></p>\n"
            "<p align=\"center\"><img src=\"images/manual-18.png\"/>　<img src=\"images/manual-19.png\"/></p>\n"
            "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(a)</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">  </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">The system main interface before ver 0.8</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(b) The system main interface of ver 0.8</span></p>\n"
            "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Figure 14</span><span style=\" font-family:\'宋体\'; font-size:12pt;\"> </span><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">Changes of main interface</span> </p></body></html>")
        elif self.ui.treeWidget.currentItem().text(0) == "6.2　Version 1.0":
            self.ui.textBrowser.setHtml(self.header +
            "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:14pt; font-weight:600;\">6.2  Version 1.0</span> </p>\n"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(1) Designs the train models interface for users to train their own models and its functions were improved.</span></p>"
            "<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:50px; margin-right:50px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,sans-serif\'; font-size:12pt;\">(2) Add a user manual to allow users to better use the system.</span></p>")
