from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
import cv2
import os


class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.setWindowModality(QtCore.Qt.NonModal)
        Options.resize(913, 980)
        Options.setMinimumSize(QtCore.QSize(913, 980))
        Options.setMaximumSize(QtCore.QSize(913, 980))
        self.groupBox_2 = QtWidgets.QGroupBox(Options)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 650, 891, 255))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(5, 35, 876, 211))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ExportSize = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.ExportSize.setObjectName("ExportSize")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ExportSize)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.ExportSize)
        self.label_17.setMinimumSize(QtCore.QSize(0, 25))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.exportSize_1 = QtWidgets.QRadioButton(self.ExportSize)
        self.exportSize_1.setMinimumSize(QtCore.QSize(0, 25))
        self.exportSize_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.exportSize_1.setFont(font)
        self.exportSize_1.setCheckable(True)
        self.exportSize_1.setChecked(False)
        self.exportSize_1.setObjectName("exportSize_1")
        self.horizontalLayout_13.addWidget(self.exportSize_1)
        self.exportSize_2 = QtWidgets.QRadioButton(self.ExportSize)
        self.exportSize_2.setMinimumSize(QtCore.QSize(0, 25))
        self.exportSize_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.exportSize_2.setFont(font)
        self.exportSize_2.setChecked(False)
        self.exportSize_2.setObjectName("exportSize_2")
        self.horizontalLayout_13.addWidget(self.exportSize_2)
        self.exportSize_width = QtWidgets.QLineEdit(self.ExportSize)
        self.exportSize_width.setEnabled(False)
        self.exportSize_width.setMinimumSize(QtCore.QSize(70, 30))
        self.exportSize_width.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exportSize_width.setFont(font)
        self.exportSize_width.setObjectName("exportSize_width")
        self.horizontalLayout_13.addWidget(self.exportSize_width)
        self.keepAspectRatio_2 = QtWidgets.QToolButton(self.ExportSize)
        self.keepAspectRatio_2.setMinimumSize(QtCore.QSize(30, 30))
        self.keepAspectRatio_2.setMaximumSize(QtCore.QSize(30, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Keep scale-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("images/Keep scale-on2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.keepAspectRatio_2.setIcon(icon)
        self.keepAspectRatio_2.setIconSize(QtCore.QSize(30, 30))
        self.keepAspectRatio_2.setCheckable(True)
        self.keepAspectRatio_2.setChecked(True)
        self.keepAspectRatio_2.setEnabled(False)
        self.keepAspectRatio_2.setAutoRaise(False)
        self.keepAspectRatio_2.setObjectName("keepAspectRatio2")
        self.horizontalLayout_13.addWidget(self.keepAspectRatio_2)
        self.exportSize_height = QtWidgets.QLineEdit(self.ExportSize)
        self.exportSize_height.setEnabled(False)
        self.exportSize_height.setMinimumSize(QtCore.QSize(70, 30))
        self.exportSize_height.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exportSize_height.setFont(font)
        self.exportSize_height.setObjectName("exportSize_height")
        self.horizontalLayout_13.addWidget(self.exportSize_height)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.ExportSize)
        self.AutoStart = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.AutoStart.setObjectName("AutoStart")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.AutoStart)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_23 = QtWidgets.QLabel(self.AutoStart)
        self.label_23.setMinimumSize(QtCore.QSize(0, 25))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_20.addWidget(self.label_23)
        self.autostart_1 = QtWidgets.QRadioButton(self.AutoStart)
        self.autostart_1.setMinimumSize(QtCore.QSize(0, 25))
        self.autostart_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.autostart_1.setFont(font)
        self.autostart_1.setAutoExclusive(True)
        self.autostart_1.setObjectName("autostart_1")
        self.horizontalLayout_20.addWidget(self.autostart_1)
        self.autostart_2 = QtWidgets.QRadioButton(self.AutoStart)
        self.autostart_2.setMinimumSize(QtCore.QSize(0, 25))
        self.autostart_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.autostart_2.setFont(font)
        self.autostart_2.setCheckable(True)
        self.autostart_2.setChecked(False)
        self.autostart_2.setAutoExclusive(True)
        self.autostart_2.setObjectName("autostart_2")
        self.horizontalLayout_20.addWidget(self.autostart_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.AutoStart)
        self.DefaultExportPath = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.DefaultExportPath.setObjectName("DefaultExportPath")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.DefaultExportPath)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_19 = QtWidgets.QLabel(self.DefaultExportPath)
        self.label_19.setMinimumSize(QtCore.QSize(0, 25))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.exportPath_1 = QtWidgets.QRadioButton(self.DefaultExportPath)
        self.exportPath_1.setMinimumSize(QtCore.QSize(0, 25))
        self.exportPath_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.exportPath_1.setFont(font)
        self.exportPath_1.setCheckable(True)
        self.exportPath_1.setChecked(False)
        self.exportPath_1.setObjectName("exportPath_1")
        self.horizontalLayout_16.addWidget(self.exportPath_1)
        self.exportPath_2 = QtWidgets.QRadioButton(self.DefaultExportPath)
        self.exportPath_2.setMinimumSize(QtCore.QSize(0, 25))
        self.exportPath_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.exportPath_2.setFont(font)
        self.exportPath_2.setObjectName("exportPath_2")
        self.horizontalLayout_16.addWidget(self.exportPath_2)
        self.exportPath_3 = QtWidgets.QLineEdit(self.DefaultExportPath)
        self.exportPath_3.setEnabled(False)
        self.exportPath_3.setMinimumSize(QtCore.QSize(0, 28))
        self.exportPath_3.setMaximumSize(QtCore.QSize(16777215, 28))
        self.exportPath_3.setFont(font)
        self.exportPath_3.setFrame(True)
        self.exportPath_3.setDragEnabled(False)
        self.exportPath_3.setReadOnly(False)
        self.exportPath_3.setObjectName("exportPath_3")
        self.horizontalLayout_16.addWidget(self.exportPath_3)
        self.Browse_3 = QtWidgets.QPushButton(self.DefaultExportPath)
        self.Browse_3.setEnabled(False)
        self.Browse_3.setMinimumSize(QtCore.QSize(0, 35))
        self.Browse_3.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Browse_3.setFont(font)
        self.Browse_3.setObjectName("Browse_3")
        self.horizontalLayout_16.addWidget(self.Browse_3)
        self.verticalLayout_4.addWidget(self.DefaultExportPath)
        self.VideoCompression = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.VideoCompression.setObjectName("VideoCompression")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.VideoCompression)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.VideoCompression)
        self.label_20.setMinimumSize(QtCore.QSize(0, 25))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.compression_1 = QtWidgets.QRadioButton(self.VideoCompression)
        self.compression_1.setMinimumSize(QtCore.QSize(0, 25))
        self.compression_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.compression_1.setFont(font)
        self.compression_1.setAutoExclusive(True)
        self.compression_1.setObjectName("compression_1")
        self.horizontalLayout_19.addWidget(self.compression_1)
        self.label_21 = QtWidgets.QLabel(self.VideoCompression)
        self.label_21.setMinimumSize(QtCore.QSize(0, 25))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.bitrate = QtWidgets.QLineEdit(self.VideoCompression)
        self.bitrate.setEnabled(False)
        self.bitrate.setMinimumSize(QtCore.QSize(70, 25))
        self.bitrate.setMaximumSize(QtCore.QSize(70, 25))
        self.bitrate.setFont(font)
        self.bitrate.setObjectName("bitrate")
        self.horizontalLayout_19.addWidget(self.bitrate)
        self.label_22 = QtWidgets.QLabel(self.VideoCompression)
        self.label_22.setMinimumSize(QtCore.QSize(0, 25))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.compression_2 = QtWidgets.QRadioButton(self.VideoCompression)
        self.compression_2.setMinimumSize(QtCore.QSize(0, 25))
        self.compression_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.compression_2.setFont(font)
        self.compression_2.setCheckable(True)
        self.compression_2.setChecked(False)
        self.compression_2.setAutoExclusive(True)
        self.compression_2.setObjectName("compression_2")
        self.horizontalLayout_19.addWidget(self.compression_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.VideoCompression)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_24.setMinimumSize(QtCore.QSize(0, 25))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 25))
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.groupBox = QtWidgets.QGroupBox(Options)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 891, 615))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(14, 49, 876, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setSpacing(15)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.previewSize_width = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.previewSize_width.setMinimumSize(QtCore.QSize(70, 0))
        self.previewSize_width.setMaximumSize(QtCore.QSize(70, 16777215))
        self.previewSize_width.setFont(font)
        self.previewSize_width.setObjectName("previewSize_width")
        self.horizontalLayout.addWidget(self.previewSize_width)
        self.keepAspectRatio = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.keepAspectRatio.setMinimumSize(QtCore.QSize(30, 30))
        self.keepAspectRatio.setMaximumSize(QtCore.QSize(30, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Keep scale-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("images/Keep scale-on2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.keepAspectRatio.setIcon(icon)
        self.keepAspectRatio.setIconSize(QtCore.QSize(30, 30))
        self.keepAspectRatio.setCheckable(True)
        self.keepAspectRatio.setChecked(True)
        self.keepAspectRatio.setAutoRaise(False)
        self.keepAspectRatio.setObjectName("keepAspectRatio")
        self.horizontalLayout.addWidget(self.keepAspectRatio)
        self.previewSize_height = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.previewSize_height.setMinimumSize(QtCore.QSize(70, 0))
        self.previewSize_height.setMaximumSize(QtCore.QSize(70, 16777215))
        self.previewSize_height.setFont(font)
        self.previewSize_height.setObjectName("previewSize_height")
        self.horizontalLayout.addWidget(self.previewSize_height)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.showFullScrean = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.showFullScrean.setFont(font)
        self.showFullScrean.setObjectName("showFullScrean")
        self.horizontalLayout.addWidget(self.showFullScrean)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.deviceNum = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.deviceNum.setMinimumSize(QtCore.QSize(40, 0))
        self.deviceNum.setMaximumSize(QtCore.QSize(40, 16777215))
        self.deviceNum.setFont(font)
        self.deviceNum.setObjectName("deviceNum")
        self.horizontalLayout_6.addWidget(self.deviceNum)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setMinimumSize(QtCore.QSize(245, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setMinimumSize(275, 0)
        self.progressBar.setFont(font)
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setHidden(True)
        self.horizontalLayout_6.addWidget(self.progressBar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.GPUNum = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.GPUNum.setMinimumSize(QtCore.QSize(40, 0))
        self.GPUNum.setMaximumSize(QtCore.QSize(40, 25))
        self.GPUNum.setFont(font)
        self.GPUNum.setObjectName("GPUNum")
        self.horizontalLayout_11.addWidget(self.GPUNum)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Source = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.Source.setMinimumSize(QtCore.QSize(0, 51))
        self.Source.setMaximumSize(QtCore.QSize(16777215, 51))
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Source)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.Source)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.log_Source_1 = QtWidgets.QRadioButton(self.Source)
        self.log_Source_1.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.log_Source_1.setFont(font)
        self.log_Source_1.setObjectName("log_Source_1")
        self.horizontalLayout_3.addWidget(self.log_Source_1)
        self.log_Source_2 = QtWidgets.QRadioButton(self.Source)
        self.log_Source_2.setFont(font)
        self.log_Source_2.setObjectName("log_Source_2")
        self.horizontalLayout_3.addWidget(self.log_Source_2)
        self.log_Source_3 = QtWidgets.QRadioButton(self.Source)
        self.log_Source_3.setFont(font)
        self.log_Source_3.setCheckable(True)
        self.log_Source_3.setChecked(False)
        self.log_Source_3.setObjectName("log_Source_3")
        self.horizontalLayout_3.addWidget(self.log_Source_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_3.addWidget(self.Source)
        self.Videos = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.Videos.setMinimumSize(QtCore.QSize(0, 51))
        self.Videos.setMaximumSize(QtCore.QSize(16777215, 51))
        self.Videos.setFont(font)
        self.Videos.setObjectName("Videos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Videos)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.Videos)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem10 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.log_Videos_1 = QtWidgets.QRadioButton(self.Videos)
        self.log_Videos_1.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.log_Videos_1.setFont(font)
        self.log_Videos_1.setCheckable(True)
        self.log_Videos_1.setChecked(False)
        self.log_Videos_1.setObjectName("log_Videos_1")
        self.horizontalLayout_4.addWidget(self.log_Videos_1)
        self.log_Videos_2 = QtWidgets.QRadioButton(self.Videos)
        self.log_Videos_2.setFont(font)
        self.log_Videos_2.setObjectName("log_Videos_2")
        self.horizontalLayout_4.addWidget(self.log_Videos_2)
        self.log_Videos_3 = QtWidgets.QRadioButton(self.Videos)
        self.log_Videos_3.setFont(font)
        self.log_Videos_3.setObjectName("log_Videos_3")
        self.horizontalLayout_4.addWidget(self.log_Videos_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_3.addWidget(self.Videos)
        self.Images = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.Images.setMinimumSize(QtCore.QSize(0, 51))
        self.Images.setMaximumSize(QtCore.QSize(16777215, 51))
        font.setKerning(True)
        self.Images.setFont(font)
        self.Images.setObjectName("Images")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Images)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.Images)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem12 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.log_Images_1 = QtWidgets.QRadioButton(self.Images)
        self.log_Images_1.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.log_Images_1.setFont(font)
        self.log_Images_1.setCheckable(True)
        self.log_Images_1.setChecked(False)
        self.log_Images_1.setObjectName("log_Images_1")
        self.horizontalLayout_5.addWidget(self.log_Images_1)
        self.log_Images_2 = QtWidgets.QRadioButton(self.Images)
        self.log_Images_2.setFont(font)
        self.log_Images_2.setChecked(False)
        self.log_Images_2.setObjectName("log_Images_2")
        self.horizontalLayout_5.addWidget(self.log_Images_2)
        self.log_Images_3 = QtWidgets.QRadioButton(self.Images)
        self.log_Images_3.setFont(font)
        self.log_Images_3.setObjectName("log_Images_3")
        self.horizontalLayout_5.addWidget(self.log_Images_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_3.addWidget(self.Images)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_23.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtWidgets.QLabel(self.widget_3)
        self.label_28.setMinimumSize(QtCore.QSize(0, 25))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.priority_1 = QtWidgets.QRadioButton(self.widget_3)
        self.priority_1.setMinimumSize(QtCore.QSize(0, 25))
        self.priority_1.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.priority_1.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priority_1.setIcon(icon1)
        self.priority_1.setCheckable(True)
        self.priority_1.setChecked(False)
        self.priority_1.setAutoExclusive(True)
        self.priority_1.setObjectName("priority_1")
        self.horizontalLayout_23.addWidget(self.priority_1)
        self.priority_2 = QtWidgets.QRadioButton(self.widget_3)
        self.priority_2.setMinimumSize(QtCore.QSize(0, 25))
        self.priority_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.priority_2.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priority_2.setIcon(icon2)
        self.priority_2.setChecked(False)
        self.priority_2.setAutoExclusive(True)
        self.priority_2.setObjectName("priority_2")
        self.horizontalLayout_23.addWidget(self.priority_2)
        spacerItem15 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem15)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.sysLogPath = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sysLogPath.setFont(font)
        self.sysLogPath.setObjectName("sysLogPath")
        self.horizontalLayout_7.addWidget(self.sysLogPath)
        self.Browse_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Browse_1.setFont(font)
        self.Browse_1.setObjectName("Browse_1")
        self.horizontalLayout_7.addWidget(self.Browse_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.temporaryPath = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.temporaryPath.setFont(font)
        self.temporaryPath.setObjectName("temporaryPath")
        self.horizontalLayout_8.addWidget(self.temporaryPath)
        self.Browse_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Browse_2.setFont(font)
        self.Browse_2.setObjectName("Browse_2")
        self.horizontalLayout_8.addWidget(self.Browse_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_22.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_27 = QtWidgets.QLabel(self.widget_2)
        self.label_27.setMinimumSize(QtCore.QSize(0, 25))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.showLargest_1 = QtWidgets.QRadioButton(self.widget_2)
        self.showLargest_1.setMinimumSize(QtCore.QSize(0, 25))
        self.showLargest_1.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.showLargest_1.setFont(font)
        self.showLargest_1.setCheckable(True)
        self.showLargest_1.setChecked(False)
        self.showLargest_1.setAutoExclusive(True)
        self.showLargest_1.setObjectName("showLargest_1")
        self.horizontalLayout_22.addWidget(self.showLargest_1)
        self.showLargest_2 = QtWidgets.QRadioButton(self.widget_2)
        self.showLargest_2.setMinimumSize(QtCore.QSize(0, 25))
        self.showLargest_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.showLargest_2.setFont(font)
        self.showLargest_2.setChecked(False)
        self.showLargest_2.setAutoExclusive(True)
        self.showLargest_2.setObjectName("showLargest_2")
        self.horizontalLayout_22.addWidget(self.showLargest_2)
        spacerItem16 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem16)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_21.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        self.autosetThres_1 = QtWidgets.QRadioButton(self.widget)
        self.autosetThres_1.setFont(font)
        self.autosetThres_1.setCheckable(True)
        self.autosetThres_1.setChecked(False)
        self.autosetThres_1.setAutoExclusive(True)
        self.autosetThres_1.setObjectName("autosetThres_1")
        self.horizontalLayout_21.addWidget(self.autosetThres_1)
        self.autosetThres_2 = QtWidgets.QRadioButton(self.widget)
        self.autosetThres_2.setFont(font)
        self.autosetThres_2.setChecked(False)
        self.autosetThres_2.setAutoExclusive(True)
        self.autosetThres_2.setObjectName("autosetThres_2")
        self.horizontalLayout_21.addWidget(self.autosetThres_2)
        spacerItem14 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem14)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_10.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.autosetmaxFPS_1 = QtWidgets.QRadioButton(self.widget1)
        self.autosetmaxFPS_1.setFont(font)
        self.autosetmaxFPS_1.setAutoExclusive(True)
        self.autosetmaxFPS_1.setObjectName("autosetmaxFPS_1")
        self.horizontalLayout_10.addWidget(self.autosetmaxFPS_1)
        self.autosetmaxFPS_2 = QtWidgets.QRadioButton(self.widget1)
        self.autosetmaxFPS_2.setFont(font)
        self.autosetmaxFPS_2.setCheckable(True)
        self.autosetmaxFPS_2.setChecked(False)
        self.autosetmaxFPS_2.setAutoExclusive(True)
        self.autosetmaxFPS_2.setObjectName("autosetmaxFPS_2")
        self.horizontalLayout_10.addWidget(self.autosetmaxFPS_2)
        spacerItem15 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.recFPS = QtWidgets.QLabel(self.widget1)
        self.recFPS.setFont(font)
        self.recFPS.setText("")
        self.recFPS.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.recFPS.setObjectName("recFPS")
        self.horizontalLayout_10.addWidget(self.recFPS)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        spacerItem16 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.verticalLayout_2.addWidget(self.widget1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Options)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 925, 561, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Save.setMinimumSize(QtCore.QSize(180, 35))
        self.Save.setMaximumSize(QtCore.QSize(180, 16777215))
        font.setPointSize(11)
        self.Save.setFont(font)
        self.Save.setObjectName("Save")
        self.horizontalLayout_9.addWidget(self.Save)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.Cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Cancel.setMinimumSize(QtCore.QSize(180, 35))
        self.Cancel.setMaximumSize(QtCore.QSize(180, 16777215))
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_9.addWidget(self.Cancel)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.RestoreDefaults = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.RestoreDefaults.setMinimumSize(QtCore.QSize(180, 35))
        self.RestoreDefaults.setMaximumSize(QtCore.QSize(180, 16777215))
        self.RestoreDefaults.setFont(font)
        self.RestoreDefaults.setObjectName("RestoreDefaults")
        self.horizontalLayout_9.addWidget(self.RestoreDefaults)

        self.retranslateUi(Options)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "Options"))
        self.groupBox_2.setTitle(_translate("Options", "Export Options"))
        self.label_17.setText(_translate("Options", "Export size:"))
        self.exportSize_1.setText(_translate("Options", "Source size"))
        self.exportSize_2.setText(_translate("Options", "Custom"))
        self.exportSize_width.setText(_translate("Options", "1280"))
        self.exportSize_height.setText(_translate("Options", "720"))
        self.label_23.setText(_translate("Options", "Automatic start:"))
        self.autostart_1.setText(_translate("Options", "Yes"))
        self.autostart_2.setText(_translate("Options", "No"))
        self.label_19.setText(_translate("Options", "Default export path:"))
        self.exportPath_1.setText(_translate("Options", "Source path"))
        self.exportPath_2.setText(_translate("Options", "Custom"))
        self.Browse_3.setText(_translate("Options", "Browse"))
        self.label_20.setText(_translate("Options", "Video compression:"))
        self.compression_1.setText(_translate("Options", "Yes"))
        self.label_21.setText(_translate("Options", "Default bitrate:"))
        self.bitrate.setText(_translate("Options", "3850"))
        self.label_22.setText(_translate("Options", "kbps"))
        self.compression_2.setText(_translate("Options", "No"))
        self.label_24.setText(
            _translate("Options", "  Compressing the video will take twice as long as normal compression."))
        self.groupBox.setTitle(_translate("Options", "General Options"))
        self.label.setText(_translate("Options", "Preview size:"))
        self.previewSize_width.setText(_translate("Options", "1280"))
        self.previewSize_height.setText(_translate("Options", "720"))
        self.showFullScrean.setText(_translate("Options", "Show full screen of preview when detecting"))
        self.label_13.setText(_translate("Options", "Capture device number:"))
        self.deviceNum.setText(_translate("Options", "1"))
        self.pushButton.setText(_translate("Options", "Check available devices"))
        self.progressBar.setFormat(_translate("Options", "%v/%m"))
        self.label_14.setText(_translate("Options", "GPU number:"))
        self.GPUNum.setText(_translate("Options", "0"))
        self.label_15.setText(_translate("Options", "If you have not any GPU, ignore it."))
        self.label_3.setText(_translate("Options", "Log test results: "))
        self.label_4.setText(_translate("Options", "Signal source"))
        self.log_Source_1.setText(_translate("Options", "Yes"))
        self.log_Source_2.setText(_translate("Options", "No"))
        self.log_Source_3.setText(_translate("Options", "Ask each time"))
        self.label_5.setText(_translate("Options", "Videos"))
        self.log_Videos_1.setText(_translate("Options", "Yes"))
        self.log_Videos_2.setText(_translate("Options", "No"))
        self.log_Videos_3.setText(_translate("Options", "Ask each time"))
        self.label_6.setText(_translate("Options", "Images"))
        self.log_Images_1.setText(_translate("Options", "Yes"))
        self.log_Images_2.setText(_translate("Options", "No"))
        self.log_Images_3.setText(_translate("Options", "Ask each time"))
        self.label_28.setText(_translate("Options", "Files detection priority:"))
        self.priority_1.setText(_translate("Options", "Videos"))
        self.priority_2.setText(_translate("Options", "Images"))
        self.label_7.setText(_translate("Options", "System log storage path:"))
        self.Browse_1.setText(_translate("Options", "Browse"))
        self.label_8.setText(_translate("Options", "Temporary files storage path:"))
        self.Browse_2.setText(_translate("Options", "Browse"))
        self.label_27.setText(_translate("Options", "Only the largest connected area is shown in result:"))
        self.showLargest_1.setText(_translate("Options", "Yes"))
        self.showLargest_2.setText(_translate("Options", "No"))
        self.label_25.setText(_translate("Options", "Automatically set the threshold for hard prediction:"))
        self.autosetThres_1.setText(_translate("Options", "Yes"))
        self.autosetThres_2.setText(_translate("Options", "No"))
        self.label_9.setText(_translate("Options", "Automatically set the maximum FPS:"))
        self.autosetmaxFPS_1.setText(_translate("Options", "Yes"))
        self.autosetmaxFPS_2.setText(_translate("Options", "No"))
        self.label_11.setText(_translate("Options", "Recommended value:"))
        self.label_12.setText(_translate("Options", "fps"))
        self.label_10.setText(
            _translate("Options", "Setting the maximum FPS can prevent video delay due to low frame counts."))
        self.Save.setText(_translate("Options", "Save"))
        self.Save.setShortcut(_translate("Options", "Return"))
        self.Cancel.setText(_translate("Options", "Cancel"))
        self.RestoreDefaults.setText(_translate("Options", "Restore Defaults"))


class win_Options(QtWidgets.QMainWindow):
    signal_options = pyqtSignal(tuple, bool, bool, int, list, str, str, int, int, str, int, tuple, int, int, str, int,
                                int, str, int, int)

    def __init__(self, parent=None):
        super(win_Options, self).__init__(parent)
        self.ui = Ui_Options()
        self.ui.setupUi(self)
        self.init_slots()

    def init_slots(self):
        self.ui.pushButton.clicked.connect(self.checkDevice)
        self.ui.Browse_1.clicked.connect(self.browse1)
        self.ui.Browse_2.clicked.connect(self.browse2)
        self.ui.Browse_3.clicked.connect(self.browse3)
        self.ui.Save.clicked.connect(self.save)
        self.ui.Cancel.clicked.connect(self.cancel)
        self.ui.RestoreDefaults.clicked.connect(self.restoreDefaults)
        self.ui.previewSize_width.textEdited.connect(self.editWidth)
        self.ui.previewSize_height.textEdited.connect(self.editHeight)
        self.ui.keepAspectRatio.clicked.connect(self.keepAspectRatio)
        self.ui.exportSize_width.textEdited.connect(self.editWidth_2)
        self.ui.exportSize_height.textEdited.connect(self.editHeight_2)
        self.ui.keepAspectRatio_2.clicked.connect(self.keepAspectRatio_2)
        self.ui.exportSize_1.clicked.connect(self.customExportSize_1)
        self.ui.exportSize_2.clicked.connect(self.customExportSize_2)
        self.ui.exportPath_1.clicked.connect(self.customExportPath_1)
        self.ui.exportPath_2.clicked.connect(self.customExportPath_2)
        self.ui.compression_1.clicked.connect(self.compression_1)
        self.ui.compression_2.clicked.connect(self.compression_2)

    def get_data(self, data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20):
        """
        Receive variables from MainWindow.
        :param data1:Preview size(tuple)
        :param data2:Keep aspect ratio(bool)
        :param data3:Show full screen of preview when detecting(bool)
        :param data4:Capture device number(int)
        :param data5:Log test results(list[int, int, int])
        :param data6:System log storage path(str)
        :param data7:Temporary files storage path(str)
        :param data8:Automatically set the threshold for hard prediction(int)
        :param data9:Automatically set the maximum FPS(int)
        :param data10:Recommended FPS value(int)
        :param data11:Whether to customize export size(int)
        :param data12:Custom export size(tuple)
        :param data13:Automatic start(int)
        :param data14:Default export path(int)
        :param data15:Custom export path(str)
        :param data16:Video compression(int)
        :param data17:Bit rate(int)
        :param data18:GPU number(str)
        :param data19:File detection priority(int)
        :param data20:Only show the largest connect area(int)
        """
        self.ui.previewSize_width.setText(str(data1[0]))
        self.ui.previewSize_height.setText(str(data1[1]))
        self.ui.keepAspectRatio.setChecked(data2)
        self.ui.showFullScrean.setChecked(data3)
        self.ui.deviceNum.setText(str(data4))
        self.ui.GPUNum.setText(data18)
        if data5[0] == 0:
            self.ui.log_Source_1.setChecked(True)
        elif data5[0] == 1:
            self.ui.log_Source_2.setChecked(True)
        elif data5[0] == 2:
            self.ui.log_Source_3.setChecked(True)
        if data5[1] == 0:
            self.ui.log_Videos_1.setChecked(True)
        elif data5[1] == 1:
            self.ui.log_Videos_2.setChecked(True)
        elif data5[1] == 2:
            self.ui.log_Videos_3.setChecked(True)
        if data5[2] == 0:
            self.ui.log_Images_1.setChecked(True)
        elif data5[2] == 1:
            self.ui.log_Images_2.setChecked(True)
        elif data5[2] == 2:
            self.ui.log_Images_3.setChecked(True)
        self.ui.sysLogPath.setText(data6)
        self.ui.temporaryPath.setText(data7)
        if data8 == 0:
            self.ui.autosetThres_1.setChecked(True)
        elif data8 == 1:
            self.ui.autosetThres_2.setChecked(True)
        if data9 == 0:
            self.ui.autosetmaxFPS_1.setChecked(True)
        elif data9 == 1:
            self.ui.autosetmaxFPS_2.setChecked(True)
        self.ui.recFPS.setText(data10)
        if data11 == 0:
            self.ui.exportSize_1.setChecked(True)
        elif data11 == 1:
            self.ui.exportSize_2.setChecked(True)
            self.ui.exportSize_width.setEnabled(True)
            self.ui.exportSize_height.setEnabled(True)
            self.ui.keepAspectRatio_2.setEnabled(True)
        self.ui.exportSize_width.setText(str(data12[0]))
        self.ui.exportSize_height.setText(str(data12[1]))
        if data13 == 0:
            self.ui.autostart_1.setChecked(True)
        elif data13 == 1:
            self.ui.autostart_2.setChecked(True)
        if data14 == 0:
            self.ui.exportPath_1.setChecked(True)
        elif data14 == 1:
            self.ui.exportPath_2.setChecked(True)
            self.ui.exportPath_3.setEnabled(True)
            self.ui.Browse_3.setEnabled(True)
        self.ui.exportPath_3.setText(data15)
        if data16 == 0:
            self.ui.compression_1.setChecked(True)
            self.ui.bitrate.setEnabled(True)
        elif data16 == 1:
            self.ui.compression_2.setChecked(True)
        if data19 == 0:
            self.ui.priority_1.setChecked(True)
        elif data19 == 1:
            self.ui.priority_2.setChecked(True)
        if data20 == 0:
            self.ui.showLargest_1.setChecked(True)
        elif data20 == 1:
            self.ui.showLargest_2.setChecked(True)
        self.ui.bitrate.setText(str(data17))
        self.ratio = data1[1] / data1[0]
        self.ratio2 = data12[1] / data12[0]

    def checkDevice(self):
        self.ui.progressBar.setHidden(False)
        device = []
        for i in range(10):
            cap = cv2.VideoCapture(i)
            if cap.isOpened():
                device.append(str(i))
            self.ui.progressBar.setValue(i + 1)
        if device:
            QMessageBox.information(self, u"System", u"The available devices include No." + ", No.".join(device))
        else:
            QMessageBox.information(self, u"System", u"There is no available device.")
        self.ui.progressBar.setHidden(True)
        self.ui.progressBar.setValue(0)

    def browse1(self):
        direct = QFileDialog.getExistingDirectory(self, "Select the system log storage path", self.ui.sysLogPath.text())
        self.ui.sysLogPath.setText(direct)

    def browse2(self):
        direct = QFileDialog.getExistingDirectory(self, "Select the temporary files storage path", self.ui.temporaryPath.text())
        self.ui.temporaryPath.setText(direct)

    def browse3(self):
        direct = QFileDialog.getExistingDirectory(self, "Select the default export path", self.ui.exportPath_3.text())
        self.ui.exportPath_3.setText(direct)

    def save(self):
        def digitCheck(string, item):
            if not string.isdigit():
                QMessageBox.warning(self, u"System", u"The %s must be a digit!" % item)
                return False
            if "number" in item and int(string) < 0:
                QMessageBox.warning(self, u"System", u"The %s is not expected to be negative!" % item)
                return False
            if "number" not in item and int(string) <= 0:
                QMessageBox.warning(self, u"System", u"The %s is must be a positive!" % item)
                return False
            return True

        if not digitCheck(self.ui.previewSize_width.text(), "width of the preview"):
            return
        if not digitCheck(self.ui.previewSize_height.text(), "height of the preview"):
            return
        if int(self.ui.previewSize_width.text()) > 15360:
            QMessageBox.warning(self, u"System", u"The width of the preview is expected to be no more than 15360!")
            return
        if int(self.ui.previewSize_height.text()) > 8640:
            QMessageBox.warning(self, u"System", u"The height of the preview is expected to be no more than 8640!")
            return
        if not digitCheck(self.ui.deviceNum.text(), "capture device number"):
            return
        if not digitCheck(self.ui.GPUNum.text(), "GPU number"):
            return
        if not digitCheck(self.ui.exportSize_width.text(), "width of export files"):
            return
        if not digitCheck(self.ui.exportSize_height.text(), "height of export files"):
            return
        if int(self.ui.exportSize_width.text()) > 15360 or int(self.ui.exportSize_height.text()) > 8640:
            if QMessageBox.question(self, "System", "The exported video size is too large, resulting in slow export "
                                    "speed and waste of memory. Do you want to reinput the export size?",
                                    QMessageBox.Yes | QMessageBox.No) == QMessageBox.Yes:
                return
        if self.ui.compression_1.isChecked() and not digitCheck(self.ui.bitrate.text(), "bit rate of the export files"):
            return
        if not os.path.exists(self.ui.sysLogPath.text()):
            QMessageBox.warning(self, u"System", u"Please check whether the path exists.")
            return
        elif not os.path.exists(self.ui.temporaryPath.text()):
            if self.ui.temporaryPath.text() != os.getcwd().replace('\\', '/') + "/temp/":  # 若临时文件存储路径为默认路径，则无需检测
                QMessageBox.warning(self, u"System", u"Please check whether the path exists.")
                return
        elif self.ui.exportPath_2.isChecked() and not os.path.exists(self.ui.exportPath_3.text()):
            QMessageBox.warning(self, u"System", u"Please heck whether the path exists.")
            return
        if self.ui.log_Source_1.isChecked():
            source = 0
        elif self.ui.log_Source_2.isChecked():
            source = 1
        else:
            source = 2
        if self.ui.log_Videos_1.isChecked():
            videos = 0
        elif self.ui.log_Videos_2.isChecked():
            videos = 1
        else:
            videos = 2
        if self.ui.log_Images_1.isChecked():
            images = 0
        elif self.ui.log_Images_2.isChecked():
            images = 1
        else:
            images = 2
        log = [source, videos, images]
        self.signal_options.emit((int(self.ui.previewSize_width.text()), int(self.ui.previewSize_height.text())), self.ui.keepAspectRatio.isChecked(), self.ui.showFullScrean.isChecked(), int(self.ui.deviceNum.text()), log, self.ui.sysLogPath.text(), self.ui.temporaryPath.text(), 0 if self.ui.autosetThres_1.isChecked() else 1, 0 if self.ui.autosetmaxFPS_1.isChecked() else 1, "", 0 if self.ui.exportSize_1.isChecked() else 1, (int(self.ui.exportSize_width.text()), int(self.ui.exportSize_height.text())), 0 if self.ui.autostart_1.isChecked() else 1, 0 if self.ui.exportPath_1.isChecked() else 1, self.ui.exportPath_3.text(), 0 if self.ui.compression_1.isChecked() else 1, int(self.ui.bitrate.text()), self.ui.GPUNum.text(), 0 if self.ui.priority_1.isChecked() else 1, 0 if self.ui.showLargest_1.isChecked() else 1)
        self.close()

    def cancel(self):
        self.close()

    def restoreDefaults(self):
        if QMessageBox.question(self, "Quit", "Are you sure to restore all default settings?",
                                QMessageBox.Yes | QMessageBox.No) == QMessageBox.Yes:
            self.ui.previewSize_width.setText("1280")
            self.ui.previewSize_height.setText("720")
            self.ui.keepAspectRatio.setChecked(True)
            self.ui.showFullScrean.setChecked(True)
            self.ui.deviceNum.setText("0")
            self.ui.GPUNum.setText("0")
            self.ui.log_Source_3.setChecked(True)
            self.ui.log_Videos_1.setChecked(True)
            self.ui.log_Images_1.setChecked(True)
            self.ui.priority_1.setChecked(True)
            self.ui.sysLogPath.setText(os.getcwd().replace('\\', '/'))
            self.ui.temporaryPath.setText(os.getcwd().replace('\\', '/') + "/temp/")
            self.ui.showLargest_1.setChecked(True)
            self.ui.autosetThres_1.setChecked(True)
            self.ui.autosetmaxFPS_2.setChecked(True)
            self.ui.exportSize_1.setChecked(True)
            self.ui.exportSize_width.setDisabled(True)
            self.ui.exportSize_height.setDisabled(True)
            self.ui.exportSize_width.setText("1280")
            self.ui.exportSize_height.setText("720")
            self.ui.autostart_2.setChecked(True)
            self.ui.exportPath_1.setChecked(True)
            self.ui.exportPath_3.setDisabled(True)
            self.ui.Browse_3.setDisabled(True)
            self.ui.exportPath_3.setText("")
            self.ui.bitrate.setDisabled(True)
            self.ui.compression_2.setChecked(True)
            self.ui.bitrate.setText("0")
            self.ratio = 128 / 72
            self.ratio2 = 128 / 72

    def editWidth(self):  # 锁定preview界面纵横比
        if self.ui.keepAspectRatio.isChecked():
            if self.ui.previewSize_width.text().isdigit():
                self.ui.previewSize_height.setText(str(int(int(self.ui.previewSize_width.text()) * self.ratio)))
            else:
                self.ui.previewSize_height.setText("")

    def editHeight(self):
        if self.ui.keepAspectRatio.isChecked():
            if self.ui.previewSize_height.text().isdigit():
                self.ui.previewSize_width.setText(str(int(int(self.ui.previewSize_height.text()) / self.ratio)))
            else:
                self.ui.previewSize_width.setText("")

    def keepAspectRatio(self):
        width, height = self.ui.previewSize_width.text(), self.ui.previewSize_height.text()
        if width.isdigit() and height.isdigit():
            if int(height) > 0 and int(width) > 0:
                self.ratio = int(height) / int(width)
                
    def editWidth_2(self):  # 锁定导出视频纵横比
        if self.ui.keepAspectRatio_2.isChecked():
            if self.ui.exportSize_width.text().isdigit():
                self.ui.exportSize_height.setText(str(int(int(self.ui.exportSize_width.text()) * self.ratio2)))
            else:
                self.ui.exportSize_height.setText("")

    def editHeight_2(self):
        if self.ui.keepAspectRatio_2.isChecked():
            if self.ui.exportSize_height.text().isdigit():
                self.ui.exportSize_width.setText(str(int(int(self.ui.exportSize_height.text()) / self.ratio2)))
            else:
                self.ui.exportSize_width.setText("")

    def keepAspectRatio_2(self):
        width, height = self.ui.exportSize_width.text(), self.ui.exportSize_height.text()
        if width.isdigit() and height.isdigit():
            if int(height) > 0 and int(width) > 0:
                self.ratio2 = int(height) / int(width)

    def customExportSize_1(self):
        self.ui.exportSize_width.setDisabled(True)
        self.ui.exportSize_height.setDisabled(True)
        self.ui.keepAspectRatio_2.setDisabled(True)
      
    def customExportSize_2(self):
        self.ui.exportSize_width.setDisabled(False)
        self.ui.exportSize_height.setDisabled(False)
        self.ui.keepAspectRatio_2.setDisabled(False)

    def customExportPath_1(self):
        self.ui.exportPath_3.setDisabled(True)
        self.ui.Browse_3.setDisabled(True)
      
    def customExportPath_2(self):
        self.ui.exportPath_3.setDisabled(False)
        self.ui.Browse_3.setDisabled(False)

    def compression_1(self):
        self.ui.bitrate.setDisabled(False)
        
    def compression_2(self):
        self.ui.bitrate.setDisabled(True)